params:
  default:
    logRetentionInDays: 3
  prd:
    logRetentionInDays: 30

custom:
  partition: aws
  org: mashukov
  subsys: url-shortener
  role: event-hub
  # global: ${file(serverless/global.yml):global}
